name: max_customer
description: "Assignment for MaxMobility interview, developed by PinkyPrerana"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.7
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  auto_route: ^10.0.1
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.3.0
  geocoding: ^3.0.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  #* Code Generation
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/logo.jpeg
